// GAME ACTIONS
export const SET_GAME_ID = 'SET_GAME_ID';
export const SET_GAME_MODE = 'SET_GAME_MODE';

// USER ACTIONS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
